version: '3.1'

services:
  db:
    platform: linux/amd64
    image: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example

  zookeeper:
    platform: linux/amd64
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    env_file:
      - zoo.env

    # https://github.com/confluentinc/examples/blob/5.1.1-post/microservices-orders/docker-compose.yml#L182-L215
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    env_file:
      - kafka.env

  init-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic utp.example.test
      "

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8081:8081"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - SERVER_PORT=8081