version: '3.1'

services:
  db:
    platform: linux/amd64
    image: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example

  zookeeper:
    platform: linux/amd64
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    env_file:
      - zoo.env

    # https://github.com/confluentinc/examples/blob/5.1.1-post/microservices-orders/docker-compose.yml#L182-L215
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    env_file:
      - kafka.env

  init-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic utp.example.test
      "

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8081:8081"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - SERVER_PORT=8081

  couchbase:
    image: couchbase
    ports:
      - "8091-8096:8091-8096"
      - "11210-11211:11210-11211"
    expose:
      - "8091-8096:8091-8096"
    volumes:
      - cb_data:/opt/couchbase/var

  couchbase-init:
    image: curlimages/curl
    depends_on:
      - couchbase
    environment:
      ADMIN_LOGIN: example
      ADMIN_PASS: example
      BUCKET: example
      LOGIN: example
      PASS: example
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      sleep 10

      echo -e 'Create couchbase cluster'
      # https://docs.couchbase.com/server/current/rest-api/rest-initialize-cluster.html#curl-syntax
      curl -v -X POST http://couchbase:8091/clusterInit \\
      -d clusterName=dev \\
      -d services=kv,index,n1ql \\
      -d username=$${ADMIN_LOGIN} \\
      -d password=$${ADMIN_PASS} \\
      -d memoryQuota=256 \\
      -d indexMemoryQuota=256 \\
      -d port=SAME

      sleep 1

      echo -e 'Create bucket'
      # https://docs.couchbase.com/server/current/rest-api/rest-bucket-create.html#curl-syntax
      curl -v -X POST http://couchbase:8091/pools/default/buckets \\
      -u $${ADMIN_LOGIN}:$${ADMIN_PASS} \\
      -d name=$${BUCKET} \\
      -d bucketType=ephemeral \\
      -d ramQuota=256 \\
      -d evictionPolicy=nruEviction \\
      -d flushEnabled=1

      sleep 1

      echo -e 'Create application user'
      # https://docs.couchbase.com/server/current/manage/manage-security/manage-users-and-roles.html#create-a-local-user-with-the-rest-api
      curl -v -X PUT http://couchbase:8091/settings/rbac/users/local/$${LOGIN} \\
      -u $${ADMIN_LOGIN}:$${ADMIN_PASS} \\
      -d password=$${PASS} \\
      -d roles=bucket_full_access[$${BUCKET}],scope_admin[$${BUCKET}]
      "

volumes:
  cb_data:
    driver: local