// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: sensitive.proto

package example_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sensitive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapKeysToRedact []string `protobuf:"bytes,1,rep,name=map_keys_to_redact,json=mapKeysToRedact,proto3" json:"map_keys_to_redact,omitempty"`
}

func (x *Sensitive) Reset() {
	*x = Sensitive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sensitive_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sensitive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sensitive) ProtoMessage() {}

func (x *Sensitive) ProtoReflect() protoreflect.Message {
	mi := &file_sensitive_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sensitive.ProtoReflect.Descriptor instead.
func (*Sensitive) Descriptor() ([]byte, []int) {
	return file_sensitive_proto_rawDescGZIP(), []int{0}
}

func (x *Sensitive) GetMapKeysToRedact() []string {
	if x != nil {
		return x.MapKeysToRedact
	}
	return nil
}

var file_sensitive_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Sensitive)(nil),
		Field:         1234,
		Name:          "example_service.sensitive",
		Tag:           "bytes,1234,opt,name=sensitive",
		Filename:      "sensitive.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional example_service.Sensitive sensitive = 1234;
	E_Sensitive = &file_sensitive_proto_extTypes[0]
)

var File_sensitive_proto protoreflect.FileDescriptor

var file_sensitive_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76,
	0x65, 0x12, 0x2b, 0x0a, 0x12, 0x6d, 0x61, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x5f, 0x74, 0x6f,
	0x5f, 0x72, 0x65, 0x64, 0x61, 0x63, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x6d,
	0x61, 0x70, 0x4b, 0x65, 0x79, 0x73, 0x54, 0x6f, 0x52, 0x65, 0x64, 0x61, 0x63, 0x74, 0x3a, 0x58,
	0x0a, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1d, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd2, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x52, 0x09, 0x73,
	0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sensitive_proto_rawDescOnce sync.Once
	file_sensitive_proto_rawDescData = file_sensitive_proto_rawDesc
)

func file_sensitive_proto_rawDescGZIP() []byte {
	file_sensitive_proto_rawDescOnce.Do(func() {
		file_sensitive_proto_rawDescData = protoimpl.X.CompressGZIP(file_sensitive_proto_rawDescData)
	})
	return file_sensitive_proto_rawDescData
}

var file_sensitive_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sensitive_proto_goTypes = []interface{}{
	(*Sensitive)(nil),                 // 0: example_service.Sensitive
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_sensitive_proto_depIdxs = []int32{
	1, // 0: example_service.sensitive:extendee -> google.protobuf.FieldOptions
	0, // 1: example_service.sensitive:type_name -> example_service.Sensitive
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sensitive_proto_init() }
func file_sensitive_proto_init() {
	if File_sensitive_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sensitive_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sensitive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sensitive_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_sensitive_proto_goTypes,
		DependencyIndexes: file_sensitive_proto_depIdxs,
		MessageInfos:      file_sensitive_proto_msgTypes,
		ExtensionInfos:    file_sensitive_proto_extTypes,
	}.Build()
	File_sensitive_proto = out.File
	file_sensitive_proto_rawDesc = nil
	file_sensitive_proto_goTypes = nil
	file_sensitive_proto_depIdxs = nil
}
